### ISSUE TITLE
Clicks on switch buttons working erraticly

### ISSUE THREAD

**Issue by boogheta** [njoyard/corona#1] opened 2020-04-02 22:43 UTC
It looks like clicking on switchers does not always work, I had a similar problem which was coming from the click action on the whole div which was cumulating with the action on the switch, I had to disable the switch event and only rely on the whole div one, it might be the same

**Comment by njoyard** [comment] 2020-04-05 14:51
I don't do any event handling myself on those but I cannot reproduce your issue. Which browser, and do you have an even random reproducing scenario?

**Comment by boogheta** [comment] 2020-04-06 08:33
so it looks like it happens whenever I try to click the switcher not on the text, neither on the switch itself, but just on the white around the switch. The cursor is still pointer, but clicking quickly enables and disables it

**Comment by njoyard** [comment] 2020-04-07 16:23
Oh indeed, looks like the UI lib I use dynamically sets an active region around the switch, and bubbling is incorrectly handled on it. I'll see if I can do something.

**Comment by njoyard** [comment] 2020-11-06 22:52
Closing, no switches in the new version.

**Closed** 2020-11-06 22:52 UTC
Labels: bug
